config/routes.rb
Rails.application.routes.draw do

  get 'welcome/loading' 

  get 'welcome/index'

  get 'welcome/sent'

  devise_for :users, :path => 'accounts' 

  resources :users, except: :create do
    member do 
      get 'unclick'
      get 'click'
    end
    resources :results 
  end

  post 'create_user' => 'users#create', as: :create_user      
  get 'reset_user' => 'users#reset', as: :reset_user 

  root 'users#show'

end

app/models/user.rb
class User < ActiveRecord::Base

	def user_full_name
		"#{user.first_name} #{user.last_name}"
	end

	def self.search_by_user_full_name(query)
    	where("(first_name || ' ' || last_name || job_title ) LIKE :q", :q => "%#{query}%")

  	end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  enum role: [:employee, :admin]
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :results
  validates_presence_of :first_name, :last_name, :job_title
  validates :email, presence: true, uniqueness: true
end

app/controllers/user/confirmations_controller.rb
class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/omniauth_callbacks_controller.rb
class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
	# before_filter :authenticate_user!, :except => [:require_no_authentication]
 	# skip_before_filter :require_no_authentication
   

  	def check_permissions
    	authorize! :create, resource
  	end

  
    

	private
  	
  	def sign_up_params
    	params.require(:user).permit(:first_name, :last_name, :job_title, :email, :password, :password_confirmation)
  	end

  	def account_update_params
    	params.require(:user).permit(:first_name, :last_name, :job_title, :email, :password, :password_confirmation, :current_password)
 	end

end

app/controllers/user/sessions_controller.rb
class User::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/user/unlocks_controller.rb
class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

		
	

	def show
		if params[:id]
			@user = User.find(params[:id])
		else
			@user = User.find(current_user)
		end
		
		@results = Result.where(user_id: @user).order(created_at: :desc)
	end

	def index

		if params[:search]
			@users = User.search_by_user_full_name(params[:search]).order(:check, :job_title, :first_name)
		
		else
			@users = User.order(:check, :job_title, :first_name)	
		end
		@all = User.all
		@count = 0
		@all.each do |user|
			if user.check == false
				@count += 1
			end
		end
	end

	

	def new
		@user = User.new
	end

	def create
		
		@user = User.create(user_params)
		@user.password = "password123"
		@user.password_confirmation = "password123"
		

		if @user.save
			UserMailer.signup_email(@user).deliver_now 
			redirect_to user_path(@user)
		else
			render :new
		end
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy

		redirect_to users_path
	end

	def reset
		@users = User.all
		@users.each do |user|
			user.check = false
			user.save
		end

		redirect_to users_path
	end

	def unclick
		@user = User.find(params[:id])
		@user.check = false
		@user.save

		redirect_to user_path(@user)
	end

	def click
		@user = User.find(params[:id])
		@user.check = true
		@user.save

		redirect_to user_path(@user)
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])

		if @user.update(edit_user_params)
			redirect_to user_path(@user)
		else
			render :edit
		end
	end



private
	
	def user_params
		params.require(:user).permit(:first_name, :last_name, :job_title, :email, :password, :password_confirmation, :role, :current_password)
	end

	def edit_user_params
		params.require(:user).permit(:first_name, :last_name, :job_title, :role)
	end

end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def peer_forms(arr)
      @arr = arr
      @reviewee = @arr[(Time.now.to_i) % (@arr.length)]
      @copy = @reviewee 
      @self_check
      #gets random peer reviewee and discards from array 
          while @reviewee == @user 

            if @arr.length == 1
              @reviewee.first_name = "me"
              return @reviewee
            else 
              @reviewee = @arr[(Time.now.to_i) % (@arr.length)] 
            end

          end 

          @arr.delete(@copy)
          @reviewee
  end
      
end

app/views/users/edit.html.erb
<style>
body {
    text-align: center;
    padding-top: 20px;
  }

</style>

<body>

  <article id="primary-content" class="animated fadeIn">


<%= simple_form_for(@user, url: user_path(@user.id), html: { method: :put }) do |f| %>
<div class="col-lg-12">
      <br>
      <div class="row">

         <div class="col-sm-4">
         <br><br>      <%= f.button :submit, "Submit", :class=>"btn btn-default form-sub-2" %>
  </div>
     <div class="col-sm-4 ">
<h5>Edit <%= "#{@user.first_name} #{@user.last_name}" %></h5>
        </div>

<div class="col-sm-4">   
<br><br>   <%= button_to "Delete Employee", @user, class: "btn btn-danger", :method => :delete, data: {confirm: "Are you sure you want to delete #{@user.first_name} #{@user.last_name} from Grouppraisal?"} %>


   </div>
   </div>
   </div>
   </div>

  
   <% if @user.errors.any? %>
  <div class="alert alert-error alert-block"><button aria-hidden="true" class="close" data-dismiss="alert" type="button">×</button>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <%= content_tag :li, msg, :id => "error_#{msg}" if msg.is_a?(String) %>
      <% end %>
    </ul>
  </div>
<% end %>

 <div class="col-lg-12">
      <br>
      <div class="row">
         <div class="col-md-4 col-md-offset-4 text-left">
            <%= f.label :first_name, class: "col-sm-6 control-label" %>
            <div class="col-sm-6">
               <%= f.text_field :first_name, placeholder: "First Name", autocomplete: "off", class: "form-control" %>
            </div>
         </div>
      </div>
   </div>
   <div class="col-lg-12">
      <br>
      <div class="row">
         <div class="col-md-4 col-md-offset-4 text-left">
            <%= f.label :last_name, class: "col-sm-6 control-label" %>
            <div class="col-sm-6">
               <%= f.text_field :last_name, placeholder: "Last Name", autocomplete: "off", class: "form-control" %>
            </div>
         </div>
      </div>
   </div>
    

 <div class="col-lg-12">
      <br>
      <div class="row">
         <div class="col-md-4 col-md-offset-4 text-left">
          <%= f.label :job_title, class: "col-sm-6 control-label" %>
            <div class="col-sm-6">
      <%= f.select :job_title, titles: ['Business Intelligence', 'Cape Town Sales Manager',  'Cape Town Sales', 'CEO', 'City Planner', 'City Planner Manager', 'CS', 'CS Manager', 'CS Team Leader', 'Durban Sales', 'Durban City Manager', 'Editorial', 'Editorial Manager', 'Finance', 'Finance Manager', 'Goods Administrator', 'Goods Manager', 'Goods Sales', 'HR Manager', 'Johannesburg Sales', 'Logistics', 'Logistics Manager', 'Pretoria Sales', 'Pretoria Sales Manager', 'Product Designer', 'PRM', 'PRM Manager', 'QA', 'Sales Manager', 'Strategic Accounts', 'Telesales', 'Telesales Manager', 'Travel', 'Business Intelligence Manager', 'Marketing Associate', 'Marketing Manager', 'Johannesburg Sales Manager', 'Strategic Accounts Manager', 'HR Trainer', 'HR Administrator'], placeholder: "Job Title" %>
  </div>
         </div>
      </div>
   </div>

  <div class="col-lg-12">
      <br>
      <div class="row">
         <div class="col-md-4 col-md-offset-4 text-left">
            <%= f.label :email, class: "col-sm-6 control-label" %>
            <div class="col-sm-6">
               <%= f.text_field :email, placeholder: "Email", autocomplete: "off", class: "form-control" %>
            </div>
         </div>
      </div>
   </div>

 <div class="col-lg-12">
      <br>
      <div class="row">
      <%= f.input :role, as: :string, label: "Check box to make admin:" do %>
        <%= f.check_box :role, {}, "admin", "employee" %>
      <% end %>
    </div>
 </div>


    <br>

 
    <% end %>


<%= link_to "Back", :back, :class => "btn btn-default"%><br>

</article>

</body>

app/views/users/index.html.erb
<style> 
.group {
	font-family: Roboto;
	font-weight: 700;
	color: black;
	font-size: 25pt;
	text-align: left;
}
.list {
	text-align: left;
	font-family: Open Sans;
	text-decoration: none;
}

.search {
	text-align: left;
}
.button-location {
	padding-top: 40pt;
}
a, a:hover, a:active, a:visited,
a.people {
	color: black;
	text-decoration: none;
}

</style>
<body>

<p><img class="loader" src="../img/loading_green.gif" HEIGHT=100% WIDTH=auto></a> </p>

<article id="primary-content" class="animated fadeIn">

<img class="back" src="https://mindofmullybizhausshoppe.files.wordpress.com/2012/10/white-rectangle-large291.gif" HEIGHT=100% WIDTH=auto>

<div class="container">
	<div class="row">
		<div class="col-md-9">
			<h1 class="group">Groupon SA Roster, <%= @count %> more appraisals to fill out</h1>
		</div>
		<div class="col-md-3">
			<div class="button-location">
				<%= button_to 'New Quarter', reset_user_path, class: "btn btn-default",  :method => :get %>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-3">
			<div class="search" style="font-family:Open Sans">
				<%= form_tag(users_path, :method => "get", id: "search-form") do %>
	    		<b/>Search by Name or Job Title: <br />
	    		<%= text_field_tag :search, params[:search], placeholder: "Search" %>
	    		<%= submit_tag "Search", class: "btn btn-default-xs" %>
				<% end %>
			</div>
		</div>
	</div>
	<br>
	<div class="row">
		
	</div>


	<div class="row">
		<div class="col-md-6">
			<% @users.each do |user| %>
				<div class="list">
					<p class ="roster" style="color:rgba(91, 201, 124, 1)"><% name = user.first_name + " " + user.last_name %>
					<a class ="people"><%= link_to name, user_path(user) %></a> - <font color=#1F221F><%= user.job_title %></font>
					<% if user.check == true %></a>
						<i class="fa fa-check-square-o"></i> 
					<% end %>
					</p></div>
			<% end %>
		</div>
	</div>

</article>
</body>

app/views/users/new.html.erb
<body><br><br><br>

<p><img class="loader" src="../img/loading_green.gif" HEIGHT=100% WIDTH=auto></a> </p>


<article id="primary-content" class="animated fadeIn">

<img class="back" src="https://mindofmullybizhausshoppe.files.wordpress.com/2012/10/white-rectangle-large291.gif" HEIGHT=100% WIDTH=auto>

  <h1>Add New Employee</h1>

  <%= simple_form_for @user, url: create_user_path do |f| %>

  <% if @user.errors.any? %>
  <div class="alert alert-error alert-block"><button aria-hidden="true" class="close" data-dismiss="alert" type="button">×</button>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <%= content_tag :li, msg, :id => "error_#{msg}" if msg.is_a?(String) %>
      <% end %>
    </ul>
  </div>
<% end %>

 <div class="col-lg-12">
      <br>
      <div class="row">
         <div class="col-md-4 col-md-offset-4 text-left">
            <%= f.label :first_name, class: "col-sm-6 control-label" %>
            <div class="col-sm-6">
               <%= f.text_field :first_name, placeholder: "First Name", autocomplete: "off", class: "form-control" %>
            </div>
         </div>
      </div>
   </div>
   <div class="col-lg-12">
      <br>
      <div class="row">
         <div class="col-md-4 col-md-offset-4 text-left">
            <%= f.label :last_name, class: "col-sm-6 control-label" %>
            <div class="col-sm-6">
               <%= f.text_field :last_name, placeholder: "Last Name", autocomplete: "off", class: "form-control" %>
            </div>
         </div>
      </div>
   </div>
    

 <div class="col-lg-12">
      <br>
      <div class="row">
         <div class="col-md-4 col-md-offset-4 text-left">
          <%= f.label :job_title, class: "col-sm-6 control-label" %>
            <div class="col-sm-6">
      <%= f.select :job_title, titles: ['Business Intelligence', 'Cape Town Sales Manager',  'Cape Town Sales', 'CEO', 'City Planner', 'City Planner Manager', 'CS', 'CS Manager', 'CS Team Leader', 'Durban Sales', 'Durban City Manager', 'Editorial', 'Editorial Manager', 'Finance', 'Finance Manager', 'Goods Administrator', 'Goods Manager', 'Goods Sales', 'HR Manager', 'Johannesburg Sales', 'Logistics', 'Logistics Manager', 'Pretoria Sales', 'Pretoria Sales Manager', 'Product Designer', 'PRM', 'PRM Manager', 'QA', 'Sales Manager', 'Strategic Accounts', 'Telesales', 'Telesales Manager', 'Travel', 'Business Intelligence Manager', 'Marketing Associate', 'Marketing Manager', 'Johannesburg Sales Manager', 'Strategic Accounts Manager', 'HR Trainer', 'HR Administrator'], placeholder: "Job Title" %>
  </div>
         </div>
      </div>
   </div>

     <div class="col-lg-12">
      <br>
      <div class="row">
         <div class="col-md-4 col-md-offset-4 text-left">
            <%= f.label :email, class: "col-sm-6 control-label" %>
            <div class="col-sm-6">
               <%= f.text_field :email, placeholder: "Email", autocomplete: "off", class: "form-control" %>
            </div>
         </div>
      </div>
   </div>

   <div class="col-lg-12">
      <br>
      <div class="row">
      <%= f.input :role, as: :string, label: "Check box to make admin:" do %>
        <%= f.check_box :role, {}, "admin", "employee" %>
      <% end %>
    </div>
 </div>


    <br>

    <div class="col-lg-12">
   <br>
      <%= f.button :submit, "Add Employee", :class=>"btn btn-default form-sub-2" %>
    </div>
    <% end %>
</article>

  </body>

app/views/users/show.html.erb
<style>
.alone {
	font-size: 50pt;
	position: relative;
	bottom: 100px;
	font-family: Roboto;
	font-weight: 700;
}
.manager {
	background-image: url(../img/logo.jpg);
	background-position: 50% 112%;
	background-repeat: no-repeat;
	background-size: 100%;
}

</style>
<body>

<p><img class="loader" src="../img/loading_green.gif" HEIGHT=100% WIDTH=auto></a> </p>
	<article id="primary-content" class="animated fadeIn">

	<img class="back" src="https://mindofmullybizhausshoppe.files.wordpress.com/2012/10/white-rectangle-large291.gif" HEIGHT=100% WIDTH=auto>
	<div class = "row">
		<div class="col-xs-2">
			<% if current_user.role == 'admin' %>
				<% if @user.role == 'employee' %>
					<div class = "delete"><%= button_to 'Edit Employee', edit_user_path(@user), class: "btn btn-danger",  :method => :get %>
					</div>
				<% end %>
			<% end %> 
		</div>
		<div class="col-xs-8">
			<% if current_user != @user %>
				<% if @user.last_name[-1] != 's' %>
					<h1>
						<%= @user.first_name %> <%= @user.last_name %>'s Appraisal Reports
						<% if @user.check == true %>
							<%= link_to "<i class='fa fa-check-square-o' style='color:black'></i>".html_safe , unclick_user_path(@user) %>
						<% else %>
						 	<%= link_to "<i class='fa fa-square-o' style='color:black'></i>".html_safe , click_user_path(@user) %>
						<% end %>
					</h1> 
					<p style="color:black" style="font-family=Open Sans"><%= @user.job_title %></p>
					
				<% else %>
					<h1>
						<%= @user.first_name %> <%= @user.last_name %>' Appraisal Reports
						<% if @user.check == true %>
							<%= link_to "<i class='fa fa-check-square-o' style='color:black'></i>".html_safe , unclick_user_path(@user) %> 
						<% end %>
					</h1>
					<p><%= @user.job_title %></p>
				<% end %>
			<% else %>
				<% if current_user.role == 'employee' %>
					<% if @results.empty? %>
						<h1 class="alone"><%= current_user.first_name %>, you do not have any appraisals at this time</h1>
					<% else %>
						<h1>Your Appraisal Reports</h1>
						<p><%= @user.first_name %> <%= @user.last_name %> - <%= @user.job_title %></p>
					<% end %>
				<% else %> 
				<div class="manager">
					<div class="alone">Hey, <%= current_user.first_name %>!
					<p><%= @user.job_title %></p></div>
				</div>
				<% end %>
			<% end %>
		</div>
		<div class="col-xs-2">
			<% if current_user.role == 'admin' && @user != current_user %>
				<div class = "add"> <%= button_to 'Add New Appraisal', new_user_result_path(@user), class: "btn btn-default",  :method => :get %>
				</div>
			<% end %> 
		</div>
	</div>


	<% if !@results.empty? %>

		<% @results.each do |result| %>
			<h2>
				<%= result.quarter %> <%= result.year %>
			</h2>
			
			<h3 style="color:black"><%= result.summary %> </h3>
			<% if current_user.role == 'admin' %>
				<%= link_to "<i class='fa fa-pencil fa-lg' style='color:black'></i>".html_safe , edit_user_result_path(result.user_id, result),  :method => :get %>  &nbsp
				<%= link_to "<i class='fa fa-trash-o fa-lg' style='color:black'></i>".html_safe, user_result_path(result.user_id, result),  :method => :delete, data: {confirm: "Are you sure you want to delete this appraisal?"} %>
			<% end %>
			
			<% if result != @results.last %>	
				<hr/>
			<% end %>
		<% end %>
	<% end %>
</article>
</body>