config/routes.rb
Rails.application.routes.draw do

  get 'welcome/loading' 

  get 'welcome/index'

  get 'welcome/sent'

  devise_for :users, :path => 'accounts' 

  resources :users, except: :create do
    member do 
      get 'unclick'
      get 'click'
    end
    resources :results 
  end

  post 'create_user' => 'users#create', as: :create_user      
  get 'reset_user' => 'users#reset', as: :reset_user 

  root 'users#show'

end

app/models/result.rb
class Result < ActiveRecord::Base
	belongs_to :user
	validates_presence_of :quarter, :year, :summary
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController

def create
    @user = User.find(params[:user_id])
    @result = @user.results.build(result_params)
    @result.user_id = @user.id

    if @result.save
      @user.check = true
      @user.save
      redirect_to user_path(@user)
    else
      render 'new'
    end
end

def new
  @user = User.find(params[:user_id])
  @result = Result.new
end


 
  def destroy
    @result = Result.find(params[:id])
    @result.destroy

    redirect_to user_path(params[:user_id])
  end

  def edit
    @result = Result.find(params[:id])
    @user = User.find(@result.user_id)
  end

  def update
    @result = Result.find(params[:id])
    @user = User.find(@result.user_id)

    if @result.update(result_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end
 
  private
    def result_params
      params.require(:result).permit(:year, :quarter, :summary)
    end

end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/results/_form.html.erb
<style type="text/css">
  .form-sub-2{
    display: block;
    margin-left: auto;
    margin-right: auto;
  }
  .field{
    color: rgba(91, 201, 124, 1);
    font-size: 20px;
  }

  textarea {
    width: 30em;
    height: 15em;
}

</style>
<div class="border-form-div-2">
<%= simple_form_for @result, url: user_results_path, method: :post do |f| %>

  <% if @result != nil %>
    <% if @result.errors.any? %>
       <div class="alert alert-error alert-block"><button aria-hidden="true" class="close" data-dismiss="alert" type="button">×</button>
        <ul>
          <% @result.errors.full_messages.each do |msg| %>
          <%= content_tag :li, msg, :id => "error_#{msg}" if msg.is_a?(String) %>
      <% end %>
        </ul>
      </div>
    <% end %>
  <% end %>
<b>
        <div class="field">
          <%= f.label :quarter %><br/>
          </div>
          <%= f.select :quarter, quarter: ['Q1', 'Q2', 'Q3', 'Q4'] %>
        <br/> <br/>
      
        <div class="field">
         <%= f.label :year %><br/>
         </div>
         <%= f.select :year, year: ['2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2025', '2026', '2027', '2028', '2029', '2030'] %>
        <br/> <br/>

        <div class="field">
         <%= f.label :summary %><br/>
         </div>
</b>
         <%= f.text_area :summary %>
        <br/> <br/>

         <%= f.button :submit, "Create Appraisal", :class=>"btn btn-default form-sub-2" %>


<% end %>
</div>

app/views/results/edit.html.erb
<style type="text/css">
  .form-sub-2{
    display: block;
    margin-left: auto;
    margin-right: auto;
  }
  .field{
    color: rgba(91, 201, 124, 1);
    font-size: 20px;
  }

  textarea {
    width: 30em;
    height: 15em;
}

</style>

<body>
<p><img class="loader" src="../img/loading_green.gif" HEIGHT=100% WIDTH=auto></a> </p>

  <article id="primary-content" class="animated fadeIn">

  <img class="back" src="https://mindofmullybizhausshoppe.files.wordpress.com/2012/10/white-rectangle-large291.gif" HEIGHT=100% WIDTH=auto>

<h1>Edit this appraisal:</h1>

<%= simple_form_for([@user, @result]) do |f| %>

    <% if @result.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@result.errors.count, "error") %> prohibited this user from being saved:</h2>
        <ul>
          <% @result.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

  <b>
        <div class="field">
          <%= f.label :quarter %><br/>
          </div>
          <%= f.select :quarter, quarter: ['Q1', 'Q2', 'Q3', 'Q4'] %>
        <br/> <br/>
      
        <div class="field">
         <%= f.label :year %><br/>
         </div>
         <%= f.select :year, year: ['2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2025', '2026', '2027', '2028', '2029', '2030'] %>
        <br/> <br/>

        <div class="field">
         <%= f.label :summary %><br/>
         </div>
  </b>
         <%= f.text_area :summary %>
        <br/> <br/>

        <div class="field">
          <%= f.button :submit, "Update Appraisal", :class=>"btn btn-default form-sub-2" %>
        </div>

<% end %>
</article>
</body>

app/views/results/new.html.erb
<body>
	<article id="primary-content" class="animated fadeIn">

<h1>Add an appraisal report for <%= @user.first_name %> <%= @user.last_name %>:</h1>
	<%= render 'results/form' %>

	</article>

</body>