config/routes.rb
Rails.application.routes.draw do

  get 'welcome/loading' 

  get 'welcome/index'

  get 'welcome/sent'

  devise_for :users, :path => 'accounts' 

  resources :users, except: :create do
    member do 
      get 'unclick'
      get 'click'
    end
    resources :results 
  end

  post 'create_user' => 'users#create', as: :create_user      
  get 'reset_user' => 'users#reset', as: :reset_user 

  root 'users#show'

end

app/views/layouts/_nav.html.erb
<style type="text/css">
.navbar-custom .navbar-nav>li>a {
  color: black;
  font-family: Roboto;
  font-weight: 700;
}
.navbar-inverse .navbar-collapse, .navbar-custom .navbar-form {
  background-color: #ececec;
}
.container-fluid {
  background-color: #ececec;
  font-size: 16pt;
  text-transform: uppercase;

}
.navbar-brand {
  font-size: 16pt;
  letter-spacing: 2px;
  color:rgba(91, 201, 124, 1);
}
.navbar-inverse .navbar-nav>li>a:hover, .navbar-inverse .navbar-nav>li>a:focus {
    color: gray;
}

</style>

<nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      		<li><a class="navbar-brand" style="color:rgba(91, 201, 124, 1)" href = "/">GROUPPRAISAL</a></li>
        	<% if current_user.role == 'admin' %>
      			<li><%= link_to 'Roster', users_path %></li>
     			  <li><%= link_to 'Send Forms' , welcome_sent_path, data: {confirm: "Are you sure you want to send this term's appraisal forms to all Groupon, South Africa employees?"} %></li>
            <li><%= link_to 'Add User', new_user_path %><li>

     		   <% end %>
      
      </ul>

      <ul class="nav navbar-nav navbar-right">
      <!--   <li>
          <% if user_signed_in? %> 
          	<br><div style="color: #82b548" >
         	<strong><%= current_user.first_name +  " "  + current_user.last_name[0] %></strong>.
          <% end %>
          </div>
        </li> -->

        <% if user_signed_in? %>
          <% if current_user.role == 'admin' %>
        	 <li><%= link_to 'Edit Profile', edit_user_registration_path, :class => 'navbar-link' %> </li>
          <% else %>
            <li><%= link_to 'Edit Account', edit_user_registration_path, :class => 'navbar-link' %></li>
          <% end %>
        	<li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %> </li>
        <% else %>
        	<li> <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> </li>
        	<li> <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %> </li>
        <% end %>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


<!-- need help on this!!! -->
<script type="text/javascript">
$(".nav li a").on("click", function(){
   $(".nav li").find(".active").removeClass("active");
   $(this).parent().addClass("active") 
});
</script>
        

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Grouppraisal</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
  <link href=<link href='http://fonts.googleapis.com/css?family=Roboto:400,700,900' rel='stylesheet' type='text/css' rel='stylesheet' type='text/css'>
</head>
<body>

<% if user_signed_in? %>
    <%= render 'layouts/nav' %>
<% end %>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
<p class="navbar-text pull-right">


<%= yield %>

</body>
</html>